### ISSUE TITLE
Silence message too short/no message errors

### ISSUE THREAD

**Issue by jlduran** [zoulasc/blocklist#2]
Just to keep you in the loop, I have filed:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264599

Essentially:

    $ ssh -l "" ssh-server

N times (N = the number of times to trigger blocklistd), and the SSH server is configured with:

    KbdInteractiveAuthentication no
    UseBlacklist yes

I am not sure if the right place to fix this is:
https://github.com/zoulasc/blocklist/blob/1b709eaa138eedb3e6e416466f63c722688fc1cb/lib/bl.c#L375
Maybe also add a validation when `ctxlen = 0`, etc. You will definitely know better.

Thank you!

**Comment by zoulasc** [comment]
I fixed it, thanks for the bug report.

**Comment by jlduran** [comment]
Amazing! Thank you!
