### ISSUE TITLE
blocklistd-helper: How it detects ipf(8)?

### ISSUE THREAD

**Issue by jlduran** [zoulasc/blocklist#7]
736e964acc74de2aeb82cd21e210bca5afdff6c0 changed the firewall detection mechanism for `ipf(8)` to look for a file named `/etc/ipfilter.conf`:

https://github.com/zoulasc/blocklist/blob/4fa16bf5f97936128fbe8c805f616d51adf02012/libexec/blocklistd-helper#L20-L25

It is my understanding that NetBSD uses [`/etc/ipf.conf`](https://man.netbsd.org/ipf.conf.5).

I just want to make sure this is indeed intended. Thank you!

**Comment by jlduran** [comment]
I have yet to test the simple patch that reverts `ipfilter` -> `ipf`.

In the meantime, for future self reference:

NetBSD: /etc/ipf.conf [^1]
FreeBSD: /etc/ipf.rules [^2]
Linux: /etc/netscript/ipfilter.conf [^3]?

[^1]: https://github.com/NetBSD/src/blob/trunk/etc/rc.d/ipfilter
[^2]: https://github.com/freebsd/freebsd-src/blob/a62d5ff5b04cb8657028c090764c3044178c4ccd/libexec/rc/rc.conf#L215
[^3]: https://packages.debian.org/sid/all/netscript-ipfilter/filelist

**Comment by zoulasc** [comment]
I think I fixed it now.

**Comment by zoulasc** [comment]
Thanks for doing all the research :-)
